---

- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: Install /etc/nginx/nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Install /etc/nginx/dhparam
  copy:
    src: dhparam
    dest: /etc/nginx/dhparam
    owner: root
    group: root
    mode: 0644

- name: Install sites to /etc/nginx/sites-available
  template:
    src: sites-available/{{ item }}.j2
    dest: /etc/nginx/sites-available/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - ntfy
    - nopaste

- name: Enable sites
  file:
    src: /etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
    state: link
  loop:
    - ntfy
    - nopaste

- name: Disabling default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create /etc/systemd/system/nginx.service.d
  file:
    path: /etc/systemd/system/nginx.service.d
    state: directory
    mode: 0755

- name: Update /etc/systemd/system/nginx.service.d/override.conf
  copy:
    src: override.conf
    dest: /etc/systemd/system/nginx.service.d/override.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure log files exist in /var/log/nginx
  copy:
    content: ""
    dest: /var/log/nginx/{{ item }}
    force: false # !
    owner: www-data
    group: adm
    mode: 0640
  loop:
    - access.log
    - access_error.log
    - error.log

- name: Add www-data user to group ntfy
  user:
    name: www-data
    groups: ntfy
    append: yes

- name: Enable and start nginx
  systemd:
    daemon-reload: yes
    name: nginx
    state: started
    enabled: yes
