all:
  hosts:
    ntfy:
      ansible_host: staging.ntfy.sh
  vars:
    ntfy_domain: "staging.ntfy.sh"
    ntfy_stats_topic: "stats-staging"
    ntfy_internal_ip: "10.116.0.2"
    nopaste_domain: "staging.nopaste.net"
