---

- name: Install pcopy
  apt:
    name: pcopy
    state: latest

- name: Update /etc/pcopy/server.conf
  copy:
    src: server.conf
    dest: /etc/pcopy/server.conf
    owner: root
    group: root
    mode: 0644

- name: Issue certificate for nopaste.net
  command:
    cmd: certbot certonly --dns-route53 -d nopaste.net --agree-tos -m philipp.heckel@gmail.com -n
    creates: /etc/letsencrypt/live/nopaste.net

- name: Enable and start pcopy
  systemd:
    daemon-reload: yes
    name: pcopy
    state: started
    enabled: yes
