---

- name: Install dependencies
  apt:
    name: jq
    state: latest

- name: Create /etc/systemd/system/node-exporter.service
  template:
    src: node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    owner: root
    group: root
    mode: 0644

- name: Reload systemd
  command:
    cmd: systemctl daemon-reload

- name: Ensure /var/lib/node_exporter exists
  file:
    path: /var/lib/node_exporter
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create /var/lib/node_exporter/installer.sh
  copy:
    src: installer.sh
    dest: /var/lib/node_exporter/installer.sh
    owner: root
    group: root
    mode: 0744

- name: Install node_exporter
  command:
    cmd: /var/lib/node_exporter/installer.sh

- name: Enable and start node-exporter
  systemd:
    daemon-reload: yes
    name: node-exporter
    state: started
    enabled: yes
