---

- name: Install fail2ban
  apt:
    name: fail2ban
    state: latest

- name: Installing fail2ban filters
  copy:
    src: filter.d/{{ item }}
    dest: /etc/fail2ban/filter.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - nginx-400.conf
    - nginx-429.conf
    - nginx-507.conf
    - manual.conf

- name: Installing fail2ban jails
  copy:
    src: jail.d/{{ item }}
    dest: /etc/fail2ban/jail.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - nginx-limit-req.local
    - nginx-400.local
    - nginx-429.local
    - nginx-507.local
    - manual.local

- name: Ensure dummy log file exists /var/log/fail2ban-manual.log
  copy:
    content: "dummy log file"
    dest: /var/log/fail2ban-manual.log
    force: false # !
    owner: root
    group: root
    mode: 0644

- name: Enable and start fail2ban
  systemd:
    daemon-reload: yes
    name: fail2ban
    state: started
    enabled: yes
